[package]
name = "texlab"
description = "LaTeX Language Server"
version = "1.10.0"
license = "GPLv3"
readme = "README.md"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = [
    "crates/bibutils",
    "crates/bibutils_sys",
    "crates/futures_boxed",
    "crates/jsonrpc", 
    "crates/jsonrpc_derive",
    "crates/texlab_citeproc",
    "crates/texlab_completion",
    "crates/texlab_distro",
    "crates/texlab_hover",
    "crates/texlab_protocol",
    "crates/texlab_symbol",
    "crates/texlab_syntax",
    "crates/texlab_test",
    "crates/texlab_workspace"]

[dependencies]
clap = "2.33"
futures = "0.3"
futures-boxed = { path = "crates/futures_boxed" }
jsonrpc = { path = "crates/jsonrpc" }
jsonrpc-derive = { path = "crates/jsonrpc_derive" }
log = "0.4.6"
once_cell = "1.3.1"
path-clean = "0.1.0"
regex = "1.3.4"
serde = { version = "1.0.104", features = ["derive", "rc"] }
serde_json = "1.0.48"
serde_repr = "0.1"
stderrlog = "0.4.1"
texlab-citeproc = { path = "crates/texlab_citeproc" }
texlab-completion = { path = "crates/texlab_completion" }
texlab-distro = { path = "crates/texlab_distro" }
texlab-hover = { path = "crates/texlab_hover" }
texlab-protocol = { path = "crates/texlab_protocol" }
texlab-symbol = { path = "crates/texlab_symbol" }
texlab-syntax = { path = "crates/texlab_syntax" }
texlab-workspace = { path = "crates/texlab_workspace" }
tokio = { version = "0.2", features = ["fs", "process"] }
tokio-util = { version = "0.3", features = ["codec"] }
uuid = { version = "0.8", features = ["v4"] }
walkdir = "2"

[dev-dependencies]
texlab-test = { path = "crates/texlab_test" }

[profile.release]
lto = true
