[package]
name = "texlab-syntax"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[dependencies]
dunce = "1.0.0"
itertools = "0.9.0"
once_cell = "1.3.1"
path-clean = "0.1.0"
serde = { version = "1.0.104", features = ["derive", "rc"] }
serde_json = "1.0.48"
texlab-distro = { path = "../texlab_distro" }
texlab-protocol = { path = "../texlab_protocol" }

[dev-dependencies]
indoc = "0.3.4"
